[build]
builder = "NIXPACKS"

[build.env]
DJANGO_SETTINGS_MODULE = "socialmanager.settings"

[build.command]
cmd = "python manage.py collectstatic --noinput"

[deploy]
startCommand = "gunicorn your_project_name.wsgi:application --bind 0.0.0.0:$PORT"
